info:
  app:
    build_time: '@git.build.time@'
    name: '@project.artifactId@'
    version: '@project.version@'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/paper?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
  jpa:
    open-in-view: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog-master.xml
  security:
    basic:
      enabled: false

management:
  endpoint:
    info:
      enabled: true

logging:
  level:
    org.springframework:
        security: debug

#security:
#  oauth2:
#    client:
#      client-id: first-client
#      client-secret: noonewilleverguess

#security:
#  oauth2:
#    resource:
#      jwt:
#        key-value: test-secret
